---
# yamllint disable rule:line-length
name: Feature Request Form
description: Make a feature request / suggestion.
body:
  - type: markdown
    attributes:
      value: |
        This form is for asking for feature requests.

  - type: dropdown
    validations:
      required: true
    attributes:
      label: If this relates to an existing add-on, please select which one.
      options:
        - Other
        - 3DPrinter-OctoPrint
        - Camera-mjpg-streamer

  - type: textarea
    validations:
      required: true
    attributes:
      label: What feature would you like to be added?
      description: Provide a clear and concise description of what you would like to have added.

  - type: markdown
    attributes:
      value: |
        ## Environment
