name: "Camera-ustreamer"
version: "2023.3.0-rc0"
slug: "camera-ustreamer"
description: "Camera streaming addon for Home Assistant, based on ustreamer."
url: "https://github.com/fredrikbaberg/ha-3dprinter-addons/tree/main/camera-ustreamer"
ingress: true
ingress_stream: true
panel_icon: mdi:camera
panel_title: ustreamer
arch:
    - armv7
    - amd64
    - armhf
    - aarch64
    - i386
stage: experimental
init: false
video: true
usb: true
ports:
    80/tcp: null
ports_description:
    80/tcp: Web-based interface (Not required for Ingress)
# options:
#     mjpg_input: "input_uvc.so -n"
# schema:
#     mjpg_input: "str"
# image: ghcr.io/fredrikbaberg/ha-addon-camera-ustreamer-{arch}
