build_from:
  aarch64:  ghcr.io/home-assistant/aarch64-base-debian:bookworm
  amd64:    ghcr.io/home-assistant/amd64-base-debian:bookworm
  armhf:    ghcr.io/home-assistant/armhf-base-debian:bookworm
  armv7:    ghcr.io/home-assistant/armv7-base-debian:bookworm
labels:
  org.opencontainers.image.title: "Home Assistant Add-on: 3DPrinter-OctoPrint"
  org.opencontainers.image.description: "3DPrinter-OctoPrint addon for Home-Assistant."
  org.opencontainers.image.source: "https://github.com/fredrikbaberg/ha-3dprinter-addons"
args:
  OCTOPRINT_VERSION: "1.9.3"
