name: "3DPrinter-Klipper"
version: "2023.01.0"
slug: "3dprinter-klipper"
description: "Klipper as an addon."
url: "https://github.com/fredrikbaberg/3dprinter-addons/tree/klipper/3dprinter-klipper"
arch:
    - armv7
    - amd64
    - armhf
    - aarch64
    - i386
stage: experimental
init: false
realtime: true
gpio: true
uart: true
usb: true
